name: Deploy to Vercel Staging and Production

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build  

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull staging environment
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_STAGING_KEY }}
        run: |
          vercel pull --yes --environment=preview \
                      --token=$VERCEL_TOKEN \
                      --scope leon-kuessners-projects \
                      --project drp-21

      - name: Deploy to staging
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_STAGING_KEY }}
        run: |
          vercel deploy --prod --confirm \
            --token=$VERCEL_TOKEN \
            --scope leon-kuessners-projects \
            --project drp-21-staging

  deploy-production:
    name: Deploy to Production
    needs: deploy-staging  # Only runs if staging passes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull production environment
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_DEPLOYMENT_KEY }}
        run: |
          vercel pull --yes --environment=production 
            --token=$VERCEL_TOKEN \
            --scope matherwafers-projects \
            --project drp-21

      - name: Deploy to production
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_DEPLOYMENT_KEY }}
        run: |
          vercel deploy --prod --confirm \
            --token=$VERCEL_TOKEN \
            --scope matherwafers-projects \
            --project drp-21
